### ISSUE TITLE
Sort sections by time (or other things)

### ISSUE THREAD

**Issue by knrafto** [colinschoen/Check-In#34]
It's hard to find the right section without ctrl-f

**Comment by colinschoen** [comment]
I am going to add the ability to sort on multiple columns and filter on multiple columns. Sorry the section page was a bit hackish as I needed to have it done and assignments done by last night.

**Comment by colinschoen** [comment]
I'll be pushing updates to make it nicer over the next few days.

**Comment by knrafto** [comment]
Thanks for your hard work! I'm just making tickets to give you a little feedback on the issues that stood out to me.

**Comment by colinschoen** [comment]
This looks to have been fixed earlier on. Closing now.
